config/routes.rb
Rails.application.routes.draw do
  resources :restaurant_opinions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'countries#index'
  resources :countries do
    get '/deletecountry', on: :collection, to: 'countries#deletecountry', as: :deletecountry
    get '/deletecity/:id', on: :collection, to: 'countries#deletecity', as: :deletecity
    get '/modifycity/:id', on: :collection, to: 'countries#modifycity', as: :modifycity
  end
  resources :cities do
    get '/create/:id', on: :collection, to: 'cities#create', as: :create
    get '/new/:id', on: :collection, to: 'cities#new', as: :new
  end
  resources :restaurants do
    get '/create/:id', on: :collection, to: 'restaurants#create', as: :create
    get '/new/:id', on: :collection, to: 'restaurants#new', as: :new
  end
  resources :hotels do
    get '/create/:id', on: :collection, to: 'hotels#create', as: :create
    get '/new/:id', on: :collection, to: 'hotels#new', as: :new
  end
  resources :activities do
    get '/create/:id', on: :collection, to: 'activities#create', as: :create
    get '/new/:id', on: :collection, to: 'activities#new', as: :new
  end
  resources :restaurant_opinions do
    get '/create/:id', on: :collection, to: 'restaurant_opinions#create', as: :create
    get '/new/:id', on: :collection, to: 'restaurant_opinions#new', as: :new
  end
  resources :hotel_opinions do
    get '/create/:id', on: :collection, to: 'hotel_opinions#create', as: :create
    get '/new/:id', on: :collection, to: 'hotel_opinions#new', as: :new
  end
  resources :activity_opinions do
    get '/create/:id', on: :collection, to: 'activity_opinions#create', as: :create
    get '/new/:id', on: :collection, to: 'activity_opinions#new', as: :new
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def show
    @restaurant = Restaurant.find(params[:id])
    @restaurantOpinions = RestaurantOpinion.where(restaurant: @restaurant.id)
  end

  def new
    @restaurant = Restaurant.new
    @@city = City.find(params[:id])
    @city = City.find(params[:id])
  end

  def create
		@restaurant = Restaurant.new
		@restaurant.city = @@city.id
		@restaurant.name = params[:restaurant][:name]
		@restaurant.address = params[:restaurant][:address]
    @restaurant.rank = params[:restaurant][:rank]

    uploaded_io = params[:restaurant][:image]
	  File.open(Rails.root.join('app', 'assets', 'images', 'restaurants', @restaurant.name + ".jpg"), 'wb') do |file|
	    file.write(uploaded_io.read)
		end

		if @restaurant.save
	  	redirect_to(@@city)
		else
	  	render "new"
		end
  end
end

app/views/restaurants/_form.html.erb
<%= form_with(model: @restaurant) do |form| %>
	<div class="field">
	  <%= form.label :name, "Nom" %>
	  <%= form.text_area :name %>
	</div>

	<div class="field">
	  <%= form.label :address, "Adresse" %>
	  <%= form.text_field :address %>
	</div>

	<div class="field">
	  <%= form.label :rank, "Rank" %>
	  <%= form.text_field :rank %>
	</div>

	<div class="field">
		<%= form.label :image, "Image" %>
    <%= form.file_field :image %>
	</div>

  <div class="actions">
    <%= form.submit "Enregistrer" %>
  </div>
<% end %>

app/views/restaurants/new.html.erb
Ajouter restaurant :</br>
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<p><%= @restaurant.address %></p>

<p>Classé <%= @restaurant.rank %> sur <%= Restaurant.count %></p>

<%= image_tag("restaurants/" + @restaurant.name + ".jpg") %></br>

<%= link_to "Ajouter un commentaire", new_restaurant_opinions_path(@restaurant.id) %></br></br>

<% @restaurantOpinions.each do |opinion| %>
  Note: <%= opinion.mark %>/5</br>
  "<%= opinion.opinion %>"</br></br>
<% end %>