config/routes.rb
Rails.application.routes.draw do
  resources :restaurant_opinions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'countries#index'
  resources :countries do
    get '/deletecountry', on: :collection, to: 'countries#deletecountry', as: :deletecountry
    get '/deletecity/:id', on: :collection, to: 'countries#deletecity', as: :deletecity
    get '/modifycity/:id', on: :collection, to: 'countries#modifycity', as: :modifycity
  end
  resources :cities do
    get '/create/:id', on: :collection, to: 'cities#create', as: :create
    get '/new/:id', on: :collection, to: 'cities#new', as: :new
  end
  resources :restaurants do
    get '/create/:id', on: :collection, to: 'restaurants#create', as: :create
    get '/new/:id', on: :collection, to: 'restaurants#new', as: :new
  end
  resources :hotels do
    get '/create/:id', on: :collection, to: 'hotels#create', as: :create
    get '/new/:id', on: :collection, to: 'hotels#new', as: :new
  end
  resources :activities do
    get '/create/:id', on: :collection, to: 'activities#create', as: :create
    get '/new/:id', on: :collection, to: 'activities#new', as: :new
  end
  resources :restaurant_opinions do
    get '/create/:id', on: :collection, to: 'restaurant_opinions#create', as: :create
    get '/new/:id', on: :collection, to: 'restaurant_opinions#new', as: :new
  end
  resources :hotel_opinions do
    get '/create/:id', on: :collection, to: 'hotel_opinions#create', as: :create
    get '/new/:id', on: :collection, to: 'hotel_opinions#new', as: :new
  end
  resources :activity_opinions do
    get '/create/:id', on: :collection, to: 'activity_opinions#create', as: :create
    get '/new/:id', on: :collection, to: 'activity_opinions#new', as: :new
  end
end

app/models/country.rb
class Country < ApplicationRecord
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
	before_action :all_countries, only: [:index, :deletecountry]
	before_action :set_country, only: [:show, :edit, :destroy, :update, :deletecity, :modifycity]
	before_action :set_cities, only: [:show, :destroy, :deletecity, :modifycity]

  def show; end


  def new
    @country = Country.new
  end

	def deletecountry;	end

	def deletecity; end

  def create
		@country = Country.new(
	  	params.require(:country).permit(:name, :description, :touristsCount)
		)

		uploaded_io = params[:country][:image]
	  File.open(Rails.root.join('app', 'assets', 'images', 'countries', @country.name + ".jpg"), 'wb') do |file|
	    file.write(uploaded_io.read)
		end

		if @country.save
	  	redirect_to(countries_path)
		else
	  	render "new"
		end
  end

  def edit; end

  def update
		@countryname = @country.name

		if @country.update(params.require(:country).permit(:name, :description, :touristsCount))
			if params[:country][:image]
				uploaded_io = params[:country][:image]
		  	File.open(Rails.root.join('app', 'assets', 'images', 'countries', @country.name + ".jpg"), 'wb') do |file|
		    	file.write(uploaded_io.read)
				end
			end

			if @countryname != @country.name
				@beginning = "app/assets/images/countries/"
				File.rename(@beginning + @countryname + ".jpg", @beginning + @country.name + ".jpg")
			end

			redirect_to(@country)
		else
	  	render 'edit'
		end
  end

  def destroy
		@cities.each do |city|
			File.delete("app/assets/images/cities/" + city.name + ".jpg")
			city.destroy
		end

		@country.destroy
		File.delete("app/assets/images/countries/" + @country.name + ".jpg")

		if Country.count == 0
			redirect_to(countries_path)
		else
			redirect_to(deletecountry_countries_path)
		end
  end

  private

	def all_countries
		@countries = Country.order('name')
	end

  def set_country
		@country = Country.find(params[:id])
  end

	def set_cities
		@cities = City.where(country: @country.id)
	end

end

app/views/countries/_form.html.erb
<%= form_with(model: country) do |form| %>
  <div class="field">
    <%= form.label :name, "Nom" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description, "Description" %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :touristsCount, "Nombre de touristes" %>
    <%= form.text_field :touristsCount %>
  </div>

  <div class="field">
    <%= form.label :image, "Image" %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
     <%= form.submit "Enregistrer" %>
  </div>
  <div class="radio_button">
  <p>Ajouter une ville a ce pays</p>
  <%= radio_button_tag(:age, "child")%>

  </div>
<% end %>

app/views/countries/deletecity.form.erb
<h1>Sélectionner une ville à supprimer</h1>

<% @cities.each do |city| %>
  <div class='image'>
    <%= link_to image_tag('cities/' + city.name + '.jpg', height: '200px'), city, method: :delete %>
  </div>
<% end %>

app/views/countries/deletecity.html.erb
<h1>Sélectionner une ville à supprimer</h1>

<% @cities.each do |city| %>
  <div class='image'>
    <%= link_to image_tag('cities/' + city.name + '.jpg', height: '200px'), city, method: :delete %>
  </div>
<% end %>

app/views/countries/deletecountry.html.erb
<h1>Sélectionner un pays à supprimer</h1>

<% @countries.each do |country| %>
  <div class='image'>
    <%= link_to image_tag('countries/' + country.name + '.jpg', height: '200px'), country, method: :delete %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Edition d'un pays</h1>

<%= render "form", country: @country %>

app/views/countries/index.html.erb
<p>
  <%= link_to 'Ajouter un pays', new_country_path %>
  <%= link_to 'Supprimer un pays', deletecountry_countries_path %></br>
</p>

<% @countries.each do |country| %>
  <div class='image'>
    <%= link_to image_tag('countries/' + country.name + '.jpg', height: '200px'), country %>
  </div>
<% end %>

app/views/countries/modifycity.html.erb
<h1>Sélectionner une ville à modifier</h1>

<h1><<%= @country.name %></h1>

<% @cities.each do |city| %>
  <div class='image'>
    <%= link_to image_tag('cities/' + city.name + '.jpg', height: '200px'), edit_city_path(city) %>
  </div>
<% end %>

app/views/countries/new.html.erb
<h1>Ajouter un pays</h1>
<%= render "form", country: @country %>

app/views/countries/show.html.erb
<p class='pays'><%= @country.name %></p>
<%= link_to 'Modifier', edit_country_path(@country) %></br>
<%= link_to 'Ajouter une ville', new_cities_path(@country) %></br>
<%= link_to 'Modifier une ville', modifycity_countries_path(@country) %></br>
<%= link_to 'Supprimer des villes', deletecity_countries_path(@country) %></br>

<%= image_tag("countries/" + @country.name + ".jpg", height: '200px') %>

<p><%= @country.touristsCount %> touristes</p>
<p><%= @country.description %></p>

<% @cities.each do |city| %>
	<div class='image'>
		<%= link_to image_tag("cities/" + city.name + ".jpg", height: "200px"), city %>
	</div>
<% end %>