config/routes.rb
Rails.application.routes.draw do
  resources :restaurant_opinions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'countries#index'
  resources :countries do
    get '/deletecountry', on: :collection, to: 'countries#deletecountry', as: :deletecountry
    get '/deletecity/:id', on: :collection, to: 'countries#deletecity', as: :deletecity
    get '/modifycity/:id', on: :collection, to: 'countries#modifycity', as: :modifycity
  end
  resources :cities do
    get '/create/:id', on: :collection, to: 'cities#create', as: :create
    get '/new/:id', on: :collection, to: 'cities#new', as: :new
  end
  resources :restaurants do
    get '/create/:id', on: :collection, to: 'restaurants#create', as: :create
    get '/new/:id', on: :collection, to: 'restaurants#new', as: :new
  end
  resources :hotels do
    get '/create/:id', on: :collection, to: 'hotels#create', as: :create
    get '/new/:id', on: :collection, to: 'hotels#new', as: :new
  end
  resources :activities do
    get '/create/:id', on: :collection, to: 'activities#create', as: :create
    get '/new/:id', on: :collection, to: 'activities#new', as: :new
  end
  resources :restaurant_opinions do
    get '/create/:id', on: :collection, to: 'restaurant_opinions#create', as: :create
    get '/new/:id', on: :collection, to: 'restaurant_opinions#new', as: :new
  end
  resources :hotel_opinions do
    get '/create/:id', on: :collection, to: 'hotel_opinions#create', as: :create
    get '/new/:id', on: :collection, to: 'hotel_opinions#new', as: :new
  end
  resources :activity_opinions do
    get '/create/:id', on: :collection, to: 'activity_opinions#create', as: :create
    get '/new/:id', on: :collection, to: 'activity_opinions#new', as: :new
  end
end

app/models/city.rb
class City < ApplicationRecord
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
	before_action :set_country, only: [:new]
	before_action :set_city, only: [:show, :edit, :destroy, :update]

  def show
		@@country = Country.find(@city.country)
		@country = Country.find(@city.country)
		@restaurants = Restaurant.where(city: @city.id)
		@hotels = Hotel.where(city: @city.id)
		@activities = Activity.where(city: @city.id)
  end

  def new
    @city = City.new
  end

  def create
		@city = City.new
		@city.name = params[:city][:name]
		@city.description = params[:city][:description]
		@city.rank = params[:city][:rank]
		@city.country = @@country.id

		uploaded_io = params[:city][:image]
	  File.open(Rails.root.join('app', 'assets', 'images', 'cities', @city.name + ".jpg"), 'wb') do |file|
	    file.write(uploaded_io.read)
		end

		if @city.save
	  	redirect_to(@city)
		else
	  	render "new"
		end
  end

  def edit;  end

  def update
		@cityname = @city.name

		if @city.update(
			params.require(:city).permit(
				:name, :country ,:description, :rank))

			if params[:city][:image]
				uploaded_io = params[:city][:image]
		  	File.open(Rails.root.join('app', 'assets', 'images', 'cities', @city.name + ".jpg"), 'wb') do |file|
		    	file.write(uploaded_io.read)
				end
			end

			if @cityname != @city.name
				@beginning = "app/assets/images/cities/"
				File.rename(@beginning + @cityname + ".jpg", @beginning + @city.name + ".jpg")
			end

			redirect_to(@city)
		else
			render 'edit'
		end
  end

  def destroy
		File.delete("app/assets/images/cities/" + @city.name + ".jpg")
		@city.destroy
		redirect_to(countries_path)
  end

  private

	def set_country
		@@country = Country.find(params[:id])
		@country = Country.find(params[:id])
	end

  def set_city
		@city = City.find(params[:id])
  end
end

app/views/cities/_form.html.erb
<%= form_with(model: city) do |form| %>
	<div class="field">
	  <%= form.label :name, "Nom" %>
	  <%= form.text_field :name %>
	</div>

	<div class="field">
	  <%= form.label :description, "Description" %>
	  <%= form.text_area :description %>
	</div>
	<div class="field">
		<%= form.label :rank, "Classement" %>
		<%= form.text_field :rank %>
	</div>

	<div class="field">
		<%= form.label :image, "Image" %>
    <%= form.file_field :image %>
	</div>

  <div class="actions">
    <%= form.submit "Enregistrer" %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<%= render "form", city: @city %>

app/views/cities/new.html.erb
<h1><%= @country.name %></h1>

<%= render "form", city: @city %>

app/views/cities/show.html.erb
<p class='pays'><%= link_to @country.name, @country %></p>

<h3 class='ville'><%= @city.name %></h3>

<%= link_to "Modifier", edit_city_path(@city) %>

<p>Classé <%= @city.rank %> sur <%= City.count %></p>
<p><%= @city.description %></p>

<%= image_tag("cities/" + @city.name + ".jpg") %>

<h3>Restaurants</h3>

<%= link_to "Ajouter un restaurant", new_restaurants_path(@city.id) %></br></br>

<% @restaurants.each do |restaurant| %>
  <%= link_to image_tag("restaurants/" + restaurant.name + ".jpg", height: '200px'), restaurant %>
<% end %>

<h3>Hotels</h3>

<%= link_to "Ajouter un hotel", new_hotels_path(@city.id) %></br></br>

<% @hotels.each do |hotel| %>
  <%= link_to image_tag("hotels/" + hotel.name + ".jpg", height: '200px'), hotel %>
<% end %>

<h3>Activités</h3>

<%= link_to "Ajouter une activité", new_activities_path(@city.id) %></br></br>

<% @activities.each do |activity| %>
  <%= link_to image_tag("activities/" + activity.name + ".jpg", height: '200px'), activity %>
<% end %>