config/routes.rb
Rails.application.routes.draw do
  resources :restaurant_opinions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'countries#index'
  resources :countries do
    get '/deletecountry', on: :collection, to: 'countries#deletecountry', as: :deletecountry
    get '/deletecity/:id', on: :collection, to: 'countries#deletecity', as: :deletecity
    get '/modifycity/:id', on: :collection, to: 'countries#modifycity', as: :modifycity
  end
  resources :cities do
    get '/create/:id', on: :collection, to: 'cities#create', as: :create
    get '/new/:id', on: :collection, to: 'cities#new', as: :new
  end
  resources :restaurants do
    get '/create/:id', on: :collection, to: 'restaurants#create', as: :create
    get '/new/:id', on: :collection, to: 'restaurants#new', as: :new
  end
  resources :hotels do
    get '/create/:id', on: :collection, to: 'hotels#create', as: :create
    get '/new/:id', on: :collection, to: 'hotels#new', as: :new
  end
  resources :activities do
    get '/create/:id', on: :collection, to: 'activities#create', as: :create
    get '/new/:id', on: :collection, to: 'activities#new', as: :new
  end
  resources :restaurant_opinions do
    get '/create/:id', on: :collection, to: 'restaurant_opinions#create', as: :create
    get '/new/:id', on: :collection, to: 'restaurant_opinions#new', as: :new
  end
  resources :hotel_opinions do
    get '/create/:id', on: :collection, to: 'hotel_opinions#create', as: :create
    get '/new/:id', on: :collection, to: 'hotel_opinions#new', as: :new
  end
  resources :activity_opinions do
    get '/create/:id', on: :collection, to: 'activity_opinions#create', as: :create
    get '/new/:id', on: :collection, to: 'activity_opinions#new', as: :new
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def show
    @activity = Activity.find(params[:id])
    @activityOpinions = ActivityOpinion.where(activity: @activity.id)
  end

  def new
    @activity = Activity.new
    @@city = City.find(params[:id])
    @city = City.find(params[:id])
  end

  def create
		@activity = Activity.new
		@activity.city = @@city.id
		@activity.name = params[:activity][:name]
		@activity.address = params[:activity][:address]
    @activity.rank = params[:activity][:rank]

    uploaded_io = params[:activity][:image]
	  File.open(Rails.root.join('app', 'assets', 'images', 'activities', @activity.name + ".jpg"), 'wb') do |file|
	    file.write(uploaded_io.read)
		end

		if @activity.save
	  	redirect_to(@@city)
		else
	  	render "new"
		end
  end
end

app/views/activities/_form.html.erb
<%= form_with(model: @activity) do |form| %>
	<div class="field">
	  <%= form.label :name, "Nom" %>
	  <%= form.text_area :name %>
	</div>

	<div class="field">
	  <%= form.label :address, "Adresse" %>
	  <%= form.text_field :address %>
	</div>

	<div class="field">
	  <%= form.label :rank, "Rank" %>
	  <%= form.text_field :rank %>
	</div>

	<div class="field">
		<%= form.label :image, "Image" %>
    <%= form.file_field :image %>
	</div>

  <div class="actions">
    <%= form.submit "Enregistrer" %>
  </div>
<% end %>

app/views/activities/new.html.erb
Ajouter activité :</br>
<%= render "form", activity: @activity %>

app/views/activities/show.html.erb
<h1><%= @activity.name %></h1>

<p><%= @activity.address %></p>

<p>Note : <%= @activity.rank %> sur <%= Activity.count %></p>

<%= image_tag("activities/" + @activity.name + ".jpg") %></br>

<%= link_to "Ajouter un commentaire", new_activity_opinions_path(@activity.id) %></br></br>

<% @activityOpinions.each do |opinion| %>
  Note: <%= opinion.mark %>/5</br>
  "<%= opinion.opinion %>"</br></br>
<% end %>